MCU_CHIP	 	= stm32f7xx
MCU_CORE     	= cortex-m7
MCU_FLOAT    	= soft
CORTEX_VER   	= $(ENV_CORTEX_VER)
OPENOCD_TARGET 	= stm32f7x

CFLAGS_COMMON += -fshort-enums -fsigned-char -mlittle-endian -mthumb -mthumb-interwork -mcpu=$(MCU_CORE) -mfloat-abi=$(MCU_FLOAT)
CFLAGS_COMMON += -DHSE_VALUE=8000000U 
CFLAGS_COMMON += -DCARIBOU_FLOAT=1 -DSTM32F746xx=1 
CFLAGS_COMMON += -DSERIAL_NO_BASE_ADDRESS=0x1FF0F420

CFLAGS_COMMON += -DUSART_QUEUE_SZ=512
CFLAGS_COMMON += -DRS485_UART=2 -DRS485_SPEED_DEF=9600 -DRS485_USE_RX_DMA=1 
CFLAGS_COMMON += -DDEBUG_USART=0 -DDEBUG_SPEED_DEF=115200

CFLAGS_COMMON += -DRS485_0_UART=5 -DRS485_0_SPEED_DEF=115200 -DRS485_0_USE_RX_DMA=1 
CFLAGS_COMMON += -DRS485_1_UART=1 -DRS485_1_SPEED_DEF=115200 -DRS485_1_USE_RX_DMA=1 

CFLAGS_COMMON += -DCARIBOU_TEST_VECTOR_BOUNDS=1

CFLAGS_COMMON += -DFEATURE_MODBUS_MASTER_PORT=rs485_x 
CFLAGS_COMMON += -DFEATURE_MODBUS_MASTER_DIR=gpio_rs485_dir_x 
CFLAGS_COMMON += -DFEATURE_MODBUS_MASTER_BAUD=115200
CFLAGS_COMMON += -DMODBUS_SLAVE_ID=2

CFLAGS_COMMON += -DXDUC_ARM_DELAY_MS=10
CFLAGS_COMMON += -DMEASURE_PERIOD=250

#
# @FIXME - clock is running too fast
#
# CFLAGS_COMMON += -DPIEZO_RX_XDUC_SAMP_HZ=500000		# Sample Freq
CFLAGS_COMMON += -DPIEZO_RX_XDUC_SAMP_HZ=250000			# Sample Freq

CFLAGS_COMMON += -DPIEZO_RX_DMA_BLOCK_SIZE=4096 		# DMA Transfer Buffer Size
CFLAGS_COMMON += -DRX_CAPTURE_SZ=\(1024*128\)			# Capture buffer size in words

CFLAGS_COMMON += -DPIEZO_RX_ADC_CHANNEL_X=8
CFLAGS_COMMON += -DPIEZO_RX_ADC_CHANNEL_Y=9

CFLAGS_COMMON += -DDEFAULT_XDUC_RX_GAIN=11
CFLAGS_COMMON += -DDEFAULT_XDUC_TX_POWER=85
CFLAGS_COMMON += -DDEFAULT_XDUC_TX_DURATION=16

CFLAGS_COMMON += -DLED0_POLARITY=true
CFLAGS_COMMON += -DBLINK_RATE_LO=125
CFLAGS_COMMON += -DBLINK_RATE_HI=64

CFLAGS_COMMON += -DBOOT_LOADER=\"LOADER.S19\"
CFLAGS_COMMON += -DBOOT_FIRMWARE=\"FIRMWARE.S19\"
CFLAGS_COMMON += -DBOOT_ARMED_TIMEOUT=4000

CFLAGS_COMMON += -DBOOT_LOAD_ADDR_BASE=0x20000000
CFLAGS_COMMON += -DBOOT_LOAD_ADDR_TOP=0x2000FFFF

CFLAGS_COMMON += -DBOOSTRAP_DEBUG=0

CFLAGS_COMMON += -DHEAP_BLOCK_SIZE=32

CFLAGS_COMMON += -DWAVESTORE_DEPTH=32
CFLAGS_COMMON += -DWAVESTORE_WIDTH=500

CFLAGS_COMMON += -DDEFAULT_XFER_PAGE_SIZE=100
CFLAGS_COMMON += -DDEFAULT_XFER_START_TIMEOUT=10000
CFLAGS_COMMON += -DDEFAULT_XFER_WAIT_TIMEOUT=5000

# sources
include ${SRC_ROOT}/_bsp/${TARGET}/_src.mk

include ${SRC_ROOT}/filesystem/_src.mk
